/* eslint-disable @typescript-eslint/no-explicit-any */
import "dotenv/config";
import mongoose from "mongoose";
import { env } from "../config/env";
import { User } from "../models/User.model";
import { Book } from "../models/Book.model";
import { Ticket } from "../models/Ticket.model";
import { Message } from "../models/Message.model";

const admins = [
  {
    authorId: "BL-ADMIN-001",
    name: "Rahul Mehta",
    email: "admin@bookleaf.in",
    password: "Admin@123",
    role: "admin" as const,
    city: "Delhi",
    joinedDate: new Date("2020-01-15"),
  },
  {
    authorId: "BL-ADMIN-002",
    name: "Saloni Mourya",
    email: "saloni@bookleaf.in",
    password: "Admin@123",
    role: "admin" as const,
    city: "Delhi",
    joinedDate: new Date("2021-03-10"),
  },
];

const authorsSeedData = [
  {
    authorId: "AUTH001",
    name: "Priya Sharma",
    email: "priya.sharma@email.com",
    password: "Author@123",
    role: "author" as const,
    phone: "+91-98765-43210",
    city: "Mumbai",
    joinedDate: new Date("2023-03-15"),
  },
  {
    authorId: "AUTH002",
    name: "Rohit Kapoor",
    email: "rohit.kapoor@email.com",
    password: "Author@123",
    role: "author" as const,
    phone: "+91-87654-32109",
    city: "Delhi",
    joinedDate: new Date("2022-11-08"),
  },
  {
    authorId: "AUTH003",
    name: "Ananya Reddy",
    email: "ananya.reddy@email.com",
    password: "Author@123",
    role: "author" as const,
    phone: "+91-76543-21098",
    city: "Hyderabad",
    joinedDate: new Date("2024-02-20"),
  },
  {
    authorId: "AUTH004",
    name: "Vikram Joshi",
    email: "vikram.joshi@email.com",
    password: "Author@123",
    role: "author" as const,
    phone: "+91-65432-10987",
    city: "Pune",
    joinedDate: new Date("2023-07-12"),
  },
  {
    authorId: "AUTH005",
    name: "Meera Nair",
    email: "meera.nair@email.com",
    password: "Author@123",
    role: "author" as const,
    phone: "+91-54321-09876",
    city: "Kochi",
    joinedDate: new Date("2023-01-05"),
  },
  {
    authorId: "AUTH006",
    name: "Arjun Malhotra",
    email: "arjun.malhotra@email.com",
    password: "Author@123",
    role: "author" as const,
    phone: "+91-43210-98765",
    city: "Chandigarh",
    joinedDate: new Date("2024-06-01"),
  },
  {
    authorId: "AUTH007",
    name: "Sneha Kulkarni",
    email: "sneha.kulkarni@email.com",
    password: "Author@123",
    role: "author" as const,
    phone: "+91-32109-87654",
    city: "Bangalore",
    joinedDate: new Date("2022-09-18"),
  },
  {
    authorId: "AUTH008",
    name: "Farhan Sheikh",
    email: "farhan.sheikh@email.com",
    password: "Author@123",
    role: "author" as const,
    phone: "+91-21098-76543",
    city: "Lucknow",
    joinedDate: new Date("2023-10-01"),
  },
  {
    authorId: "AUTH009",
    name: "Kavita Deshmukh",
    email: "kavita.deshmukh@email.com",
    password: "Author@123",
    role: "author" as const,
    phone: "+91-10987-65432",
    city: "Nagpur",
    joinedDate: new Date("2024-04-10"),
  },
  {
    authorId: "AUTH010",
    name: "Diya Chatterjee",
    email: "diya.chatterjee@email.com",
    password: "Author@123",
    role: "author" as const,
    phone: "+91-09876-54321",
    city: "Kolkata",
    joinedDate: new Date("2023-05-22"),
  },
];

function buildBooks(authorIdMap: Record<string, string>) {
  return [
    {
      bookId: "BK001",
      authorId: authorIdMap["AUTH001"],
      title: "Whispers of the Ganges",
      isbn: "978-93-5XXXX-01-1",
      genre: "Literary Fiction",
      publicationDate: new Date("2023-06-20"),
      status: "Published & Live" as const,
      mrp: 399,
      printingCostPerCopy: 80,
      authorRoyaltyPerCopy: 35,
      totalCopiesSold: 342,
      totalRoyaltyEarned: 11970,
      royaltyPaid: 8400,
      royaltyPending: 3570,
      lastRoyaltyPayoutDate: new Date("2025-10-15"),
      printPartner: "In-House" as const,
      availableOn: ["Amazon India", "Flipkart", "BookLeaf Store"],
    },
    {
      bookId: "BK002",
      authorId: authorIdMap["AUTH001"],
      title: "The Saffron Diaries",
      isbn: "978-93-5XXXX-02-8",
      genre: "Non-Fiction / Memoir",
      publicationDate: new Date("2024-01-10"),
      status: "Published & Live" as const,
      mrp: 450,
      printingCostPerCopy: 90,
      authorRoyaltyPerCopy: 42,
      totalCopiesSold: 189,
      totalRoyaltyEarned: 7938,
      royaltyPaid: 7938,
      royaltyPending: 0,
      lastRoyaltyPayoutDate: new Date("2025-12-01"),
      printPartner: "In-House" as const,
      availableOn: ["Amazon India", "BookLeaf Store"],
    },
    {
      bookId: "BK003",
      authorId: authorIdMap["AUTH002"],
      title: "Code & Karma",
      isbn: "978-93-5XXXX-03-5",
      genre: "Self-Help / Technology",
      publicationDate: new Date("2023-02-14"),
      status: "Published & Live" as const,
      mrp: 350,
      printingCostPerCopy: 70,
      authorRoyaltyPerCopy: 30,
      totalCopiesSold: 876,
      totalRoyaltyEarned: 26280,
      royaltyPaid: 21000,
      royaltyPending: 5280,
      lastRoyaltyPayoutDate: new Date("2025-09-01"),
      printPartner: "Repro India" as const,
      availableOn: ["Amazon India", "Flipkart", "Amazon US", "BookLeaf Store"],
    },
    {
      bookId: "BK004",
      authorId: authorIdMap["AUTH002"],
      title: "Startup Sutra",
      isbn: "978-93-5XXXX-04-2",
      genre: "Business / Entrepreneurship",
      publicationDate: new Date("2024-05-22"),
      status: "Published & Live" as const,
      mrp: 499,
      printingCostPerCopy: 100,
      authorRoyaltyPerCopy: 48,
      totalCopiesSold: 1203,
      totalRoyaltyEarned: 57744,
      royaltyPaid: 50000,
      royaltyPending: 7744,
      lastRoyaltyPayoutDate: new Date("2025-11-15"),
      printPartner: "In-House" as const,
      availableOn: ["Amazon India", "Flipkart", "Amazon US", "Amazon UK", "BookLeaf Store"],
    },
    {
      bookId: "BK005",
      authorId: authorIdMap["AUTH003"],
      title: "Between Two Temples",
      isbn: "978-93-5XXXX-05-9",
      genre: "Historical Fiction",
      publicationDate: new Date("2024-07-05"),
      status: "Published & Live" as const,
      mrp: 425,
      printingCostPerCopy: 85,
      authorRoyaltyPerCopy: 38,
      totalCopiesSold: 67,
      totalRoyaltyEarned: 2546,
      royaltyPaid: 0,
      royaltyPending: 2546,
      lastRoyaltyPayoutDate: undefined,
      printPartner: "Epitome Books" as const,
      availableOn: ["Amazon India", "BookLeaf Store"],
    },
    {
      bookId: "BK006",
      authorId: authorIdMap["AUTH004"],
      title: "Debugging Life",
      isbn: "978-93-5XXXX-06-6",
      genre: "Self-Help",
      publicationDate: new Date("2023-11-30"),
      status: "Published & Live" as const,
      mrp: 299,
      printingCostPerCopy: 60,
      authorRoyaltyPerCopy: 25,
      totalCopiesSold: 534,
      totalRoyaltyEarned: 13350,
      royaltyPaid: 10000,
      royaltyPending: 3350,
      lastRoyaltyPayoutDate: new Date("2025-08-20"),
      printPartner: "In-House" as const,
      availableOn: ["Amazon India", "Flipkart", "BookLeaf Store"],
    },
    {
      bookId: "BK007",
      authorId: authorIdMap["AUTH004"],
      title: "The Last Monsoon",
      isbn: "978-93-5XXXX-07-3",
      genre: "Poetry",
      publicationDate: new Date("2024-08-15"),
      status: "Published & Live" as const,
      mrp: 199,
      printingCostPerCopy: 40,
      authorRoyaltyPerCopy: 15,
      totalCopiesSold: 123,
      totalRoyaltyEarned: 1845,
      royaltyPaid: 1845,
      royaltyPending: 0,
      lastRoyaltyPayoutDate: new Date("2025-12-01"),
      printPartner: "In-House" as const,
      availableOn: ["Amazon India", "BookLeaf Store"],
    },
    {
      bookId: "BK008",
      authorId: authorIdMap["AUTH005"],
      title: "Cardamom & Chaos",
      isbn: "978-93-5XXXX-08-0",
      genre: "Contemporary Fiction",
      publicationDate: new Date("2023-04-18"),
      status: "Published & Live" as const,
      mrp: 375,
      printingCostPerCopy: 75,
      authorRoyaltyPerCopy: 32,
      totalCopiesSold: 445,
      totalRoyaltyEarned: 14240,
      royaltyPaid: 14240,
      royaltyPending: 0,
      lastRoyaltyPayoutDate: new Date("2025-12-01"),
      printPartner: "Repro India" as const,
      availableOn: ["Amazon India", "Flipkart", "BookLeaf Store"],
    },
    {
      bookId: "BK009",
      authorId: authorIdMap["AUTH005"],
      title: "Letters from Lakshadweep",
      isbn: "978-93-5XXXX-09-7",
      genre: "Travel / Non-Fiction",
      publicationDate: new Date("2024-03-01"),
      status: "Published & Live" as const,
      mrp: 550,
      printingCostPerCopy: 110,
      authorRoyaltyPerCopy: 55,
      totalCopiesSold: 201,
      totalRoyaltyEarned: 11055,
      royaltyPaid: 8000,
      royaltyPending: 3055,
      lastRoyaltyPayoutDate: new Date("2025-10-15"),
      printPartner: "In-House" as const,
      availableOn: ["Amazon India", "Amazon US", "BookLeaf Store"],
    },
    {
      bookId: "BK010",
      authorId: authorIdMap["AUTH006"],
      title: "Turban Tales",
      isbn: "978-93-5XXXX-10-3",
      genre: "Humor / Essays",
      publicationDate: new Date("2024-09-10"),
      status: "Published & Live" as const,
      mrp: 325,
      printingCostPerCopy: 65,
      authorRoyaltyPerCopy: 28,
      totalCopiesSold: 88,
      totalRoyaltyEarned: 2464,
      royaltyPaid: 0,
      royaltyPending: 2464,
      lastRoyaltyPayoutDate: undefined,
      printPartner: "In-House" as const,
      availableOn: ["Amazon India", "BookLeaf Store"],
    },
    {
      bookId: "BK011",
      authorId: authorIdMap["AUTH007"],
      title: "The Algorithm of Love",
      isbn: "978-93-5XXXX-11-0",
      genre: "Romance",
      publicationDate: new Date("2022-12-25"),
      status: "Published & Live" as const,
      mrp: 299,
      printingCostPerCopy: 60,
      authorRoyaltyPerCopy: 25,
      totalCopiesSold: 1567,
      totalRoyaltyEarned: 39175,
      royaltyPaid: 35000,
      royaltyPending: 4175,
      lastRoyaltyPayoutDate: new Date("2025-11-15"),
      printPartner: "Repro India" as const,
      availableOn: ["Amazon India", "Flipkart", "Amazon US", "BookLeaf Store"],
    },
    {
      bookId: "BK012",
      authorId: authorIdMap["AUTH007"],
      title: "Ctrl+Alt+Delete My Ex",
      isbn: "978-93-5XXXX-12-7",
      genre: "Romance / Humor",
      publicationDate: new Date("2024-02-14"),
      status: "Published & Live" as const,
      mrp: 350,
      printingCostPerCopy: 70,
      authorRoyaltyPerCopy: 30,
      totalCopiesSold: 723,
      totalRoyaltyEarned: 21690,
      royaltyPaid: 18000,
      royaltyPending: 3690,
      lastRoyaltyPayoutDate: new Date("2025-10-15"),
      printPartner: "In-House" as const,
      availableOn: ["Amazon India", "Flipkart", "BookLeaf Store"],
    },
    {
      bookId: "BK013",
      authorId: authorIdMap["AUTH007"],
      title: "Midnight in Mysore",
      isbn: "978-93-5XXXX-13-4",
      genre: "Thriller",
      publicationDate: undefined,
      status: "Cover Design" as const,
      mrp: 0,
      printingCostPerCopy: 0,
      authorRoyaltyPerCopy: 0,
      totalCopiesSold: 0,
      totalRoyaltyEarned: 0,
      royaltyPaid: 0,
      royaltyPending: 0,
      lastRoyaltyPayoutDate: undefined,
      printPartner: "In-House" as const,
      availableOn: [],
    },
    {
      bookId: "BK014",
      authorId: authorIdMap["AUTH008"],
      title: "Ghazal of the Forgotten",
      isbn: "978-93-5XXXX-14-1",
      genre: "Poetry / Urdu Literature",
      publicationDate: new Date("2024-01-26"),
      status: "Published & Live" as const,
      mrp: 250,
      printingCostPerCopy: 50,
      authorRoyaltyPerCopy: 20,
      totalCopiesSold: 156,
      totalRoyaltyEarned: 3120,
      royaltyPaid: 3120,
      royaltyPending: 0,
      lastRoyaltyPayoutDate: new Date("2025-12-01"),
      printPartner: "Epitome Books" as const,
      availableOn: ["Amazon India", "BookLeaf Store"],
    },
    {
      bookId: "BK015",
      authorId: authorIdMap["AUTH009"],
      title: "Raising Roots",
      isbn: "978-93-5XXXX-15-8",
      genre: "Parenting / Non-Fiction",
      publicationDate: undefined,
      status: "Typesetting" as const,
      mrp: 0,
      printingCostPerCopy: 0,
      authorRoyaltyPerCopy: 0,
      totalCopiesSold: 0,
      totalRoyaltyEarned: 0,
      royaltyPaid: 0,
      royaltyPending: 0,
      lastRoyaltyPayoutDate: undefined,
      printPartner: "In-House" as const,
      availableOn: [],
    },
    {
      bookId: "BK016",
      authorId: authorIdMap["AUTH009"],
      title: "The Nagpur Notebooks",
      isbn: "978-93-5XXXX-16-5",
      genre: "Essays / Memoir",
      publicationDate: new Date("2024-11-05"),
      status: "Published & Live" as const,
      mrp: 299,
      printingCostPerCopy: 60,
      authorRoyaltyPerCopy: 25,
      totalCopiesSold: 34,
      totalRoyaltyEarned: 850,
      royaltyPaid: 0,
      royaltyPending: 850,
      lastRoyaltyPayoutDate: undefined,
      printPartner: "In-House" as const,
      availableOn: ["Amazon India", "BookLeaf Store"],
    },
    {
      bookId: "BK017",
      authorId: authorIdMap["AUTH010"],
      title: "Durga's Daughters",
      isbn: "978-93-5XXXX-17-2",
      genre: "Literary Fiction",
      publicationDate: new Date("2023-10-15"),
      status: "Published & Live" as const,
      mrp: 475,
      printingCostPerCopy: 95,
      authorRoyaltyPerCopy: 45,
      totalCopiesSold: 612,
      totalRoyaltyEarned: 27540,
      royaltyPaid: 25000,
      royaltyPending: 2540,
      lastRoyaltyPayoutDate: new Date("2025-11-15"),
      printPartner: "Repro India" as const,
      availableOn: ["Amazon India", "Flipkart", "Amazon US", "BookLeaf Store"],
    },
    {
      bookId: "BK018",
      authorId: authorIdMap["AUTH010"],
      title: "Howrah Nights",
      isbn: "978-93-5XXXX-18-9",
      genre: "Crime / Thriller",
      publicationDate: new Date("2025-01-20"),
      status: "Published & Live" as const,
      mrp: 399,
      printingCostPerCopy: 80,
      authorRoyaltyPerCopy: 35,
      totalCopiesSold: 45,
      totalRoyaltyEarned: 1575,
      royaltyPaid: 0,
      royaltyPending: 1575,
      lastRoyaltyPayoutDate: undefined,
      printPartner: "In-House" as const,
      availableOn: ["Amazon India", "BookLeaf Store"],
    },
  ];
}

function buildTickets(
  authorIdMap: Record<string, string>,
  bookIdMap: Record<string, string>,
  adminIds: string[]
) {
  return [
    {
      ticketNumber: "BL-2025-0001",
      authorId: authorIdMap["AUTH003"],
      bookId: bookIdMap["BK005"],
      subject: "I have never received any royalty for Between Two Temples",
      description: "My book Between Two Temples was published in July 2024. It has sold 67 copies and I can see Rs 2,546 as royalty earned in the dashboard. But I have never received a single payment. My bank account is linked. This is very frustrating. Please look into this urgently.",
      category: "Royalty & Payments",
      priority: "Critical",
      status: "Open",
      assignedTo: null,
      aiClassification: "Royalty & Payments",
      aiPriority: "Critical",
      aiDraftResponse: "Ananya, I completely understand your frustration. Between Two Temples has earned Rs 2,546 in royalties since July 2024 and you have not received a single payment, which is not acceptable. I am escalating this directly to our accounts team right now as a priority case. You will receive either a payment confirmation or a detailed explanation within 48 hours.",
      aiError: false,
      categoryOverridden: false,
      priorityOverridden: false,
    },
    {
      ticketNumber: "BL-2025-0002",
      authorId: authorIdMap["AUTH002"],
      bookId: bookIdMap["BK003"],
      subject: "Wrong ISBN showing on Amazon for Code and Karma",
      description: "The ISBN printed on my physical copy of Code and Karma is 978-93-5XXXX-03-5. But Amazon India is showing a completely different ISBN on the listing page. This is causing confusion for readers. Please fix this as soon as possible.",
      category: "ISBN & Metadata Issues",
      priority: "Critical",
      status: "In Progress",
      assignedTo: adminIds[0],
      aiClassification: "ISBN & Metadata Issues",
      aiPriority: "Critical",
      aiDraftResponse: "Rohit, an ISBN mismatch between your physical copy and the Amazon listing is a serious data issue. I have immediately flagged this to our production team. They will trace where the discrepancy occurred and push the correct ISBN to Amazon within 48 hours.",
      aiError: false,
      categoryOverridden: false,
      priorityOverridden: false,
    },
    {
      ticketNumber: "BL-2025-0003",
      authorId: authorIdMap["AUTH002"],
      bookId: bookIdMap["BK004"],
      subject: "Royalty amount for Startup Sutra seems lower than expected",
      description: "Startup Sutra has sold 1203 copies at MRP Rs 499. The dashboard shows Rs 57,744 earned but only Rs 50,000 paid. That means Rs 7,744 is still pending. Can you explain when this will be paid?",
      category: "Royalty & Payments",
      priority: "High",
      status: "In Progress",
      assignedTo: adminIds[0],
      aiClassification: "Royalty & Payments",
      aiPriority: "High",
      aiDraftResponse: "Rohit, your royalty calculation is correct. Startup Sutra has earned Rs 57,744 total on 1,203 copies. The Rs 7,744 pending balance is scheduled for the next quarterly payout. Royalties are calculated at end of each quarter and paid within 45 days.",
      aiError: false,
      categoryOverridden: false,
      priorityOverridden: false,
    },
    {
      ticketNumber: "BL-2025-0004",
      authorId: authorIdMap["AUTH005"],
      bookId: bookIdMap["BK009"],
      subject: "Letters from Lakshadweep showing as unavailable on Amazon US",
      description: "My book Letters from Lakshadweep has been showing as Currently Unavailable on Amazon US for the past 4 days. It is still fine on Amazon India. My international readers are messaging me. Can you please fix it?",
      category: "Distribution & Availability",
      priority: "Medium",
      status: "Resolved",
      assignedTo: adminIds[1],
      aiClassification: "Distribution & Availability",
      aiPriority: "Medium",
      aiDraftResponse: null,
      aiError: false,
      categoryOverridden: false,
      priorityOverridden: false,
    },
    {
      ticketNumber: "BL-2025-0005",
      authorId: authorIdMap["AUTH007"],
      bookId: bookIdMap["BK013"],
      subject: "Cover design for Midnight in Mysore has been pending for 4 weeks",
      description: "My manuscript for Midnight in Mysore was submitted over 4 weeks ago. I can see the status shows Cover Design in my dashboard but there has been no update or proof sent to me.",
      category: "Book Status & Production Updates",
      priority: "Medium",
      status: "Open",
      assignedTo: null,
      aiClassification: "Book Status & Production Updates",
      aiPriority: "Medium",
      aiDraftResponse: "Sneha, Midnight in Mysore is currently with our cover design team. I checked and they completed a first concept last week. The proof was sent to your registered email. Please check your spam folder for an email from design@bookleaf.in.",
      aiError: false,
      categoryOverridden: false,
      priorityOverridden: false,
    },
    {
      ticketNumber: "BL-2025-0006",
      authorId: authorIdMap["AUTH009"],
      bookId: bookIdMap["BK015"],
      subject: "Can I update the book description for Raising Roots before it is published",
      description: "My book Raising Roots is currently in the typesetting stage. I want to make a small change to the book description that will appear on Amazon and Flipkart. Is it possible to update this before the book goes live?",
      category: "General Inquiry",
      priority: "Low",
      status: "Open",
      assignedTo: null,
      aiClassification: "General Inquiry",
      aiPriority: "Low",
      aiDraftResponse: "Kavita, yes you can absolutely update the book description before Raising Roots goes live. Since your book is still in typesetting, the metadata has not been submitted to the distribution platforms yet. Just reply to this ticket with your updated description.",
      aiError: false,
      categoryOverridden: false,
      priorityOverridden: false,
    },
    {
      ticketNumber: "BL-2025-0007",
      authorId: authorIdMap["AUTH004"],
      bookId: bookIdMap["BK006"],
      subject: "Author copies of Debugging Life have blurry images and misaligned pages",
      description: "I just received my 10 author copies of Debugging Life and the quality is very disappointing. The images in Chapter 3 and Chapter 7 are blurry. Also pages 45-52 appear to be slightly misaligned. Can you please arrange a reprint?",
      category: "Printing & Quality",
      priority: "High",
      status: "Open",
      assignedTo: null,
      aiClassification: "Printing & Quality",
      aiPriority: "High",
      aiDraftResponse: "Vikram, I am really sorry about the quality of your author copies. Please share photos of the defective pages by replying to this ticket. As soon as we verify the issue, we will arrange a complete free reprint of all 10 copies within 5-7 business days.",
      aiError: false,
      categoryOverridden: false,
      priorityOverridden: false,
    },
  ];
}

async function seed() {
  console.log("Connecting to MongoDB...");
  await mongoose.connect(env.MONGODB_URI);
  console.log("Connected");

  console.log("Clearing existing data...");
  await Promise.all([
    User.deleteMany({}),
    Book.deleteMany({}),
    Ticket.deleteMany({}),
    Message.deleteMany({}),
  ]);
  console.log("Cleared");

 console.log("Seeding admins...");
const seededAdmins = [];
for (const admin of admins) {
  const u = new User(admin);
  await u.save();
  seededAdmins.push(u);
}
const adminIds = seededAdmins.map((a: any) => a._id.toString());

console.log("Seeding authors...");
const seededAuthors = [];
for (const author of authorsSeedData) {
  const u = new User(author);
  await u.save();
  seededAuthors.push(u);
}
  const authorIdMap: Record<string, string> = {};
  seededAuthors.forEach((a: any) => {
    authorIdMap[a.authorId] = a._id.toString();
  });

  console.log("Seeding books...");
  const booksData = buildBooks(authorIdMap);
  const seededBooks = await Book.insertMany(booksData);

  const bookIdMap: Record<string, string> = {};
  seededBooks.forEach((b: any) => {
    bookIdMap[b.bookId] = b._id.toString();
  });

  console.log("Seeding tickets...");
  const ticketsData = buildTickets(authorIdMap, bookIdMap, adminIds);
  const seededTickets = await Ticket.insertMany(ticketsData);

  const resolvedTicket = seededTickets.find((t: any) => t.status === "Resolved");
  if (resolvedTicket) {
    const meera = seededAuthors.find((a: any) => a.authorId === "AUTH005");
    await Message.insertMany([
      {
        ticketId: (resolvedTicket as any)._id,
        senderId: meera?._id,
        senderRole: "author",
        message: "My book Letters from Lakshadweep has been showing as Currently Unavailable on Amazon US for the past 4 days. Can you please fix this?",
        isFromAIDraft: false,
      },
      {
        ticketId: (resolvedTicket as any)._id,
        senderId: seededAdmins[1]._id,
        senderRole: "admin",
        message: "Hi Meera, this is a stock sync issue with Amazon US. I have triggered a re-sync with our distribution partner. Your book should be showing as available within 24-48 hours. Sorry for the inconvenience!",
        isFromAIDraft: false,
      },
    ]);
  }

  console.log("");
  console.log("Seed complete!");
  console.log("ADMIN ACCOUNTS:");
  console.log("  admin@bookleaf.in     Password: Admin@123");
  console.log("  saloni@bookleaf.in    Password: Admin@123");
  console.log("");
  console.log("AUTHOR ACCOUNTS (password: Author@123):");
  authorsSeedData.forEach((a) => {
    console.log("  " + a.email + " - " + a.name);
  });

  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});